### ISSUE TITLE
Prevent imported feature files from changing existing issue data

### ISSUE THREAD

**Issue by csvtuda** [Qytera-Gmbh/cypress-xray-plugin#100]
When importing feature files during feature file synchronization, any existing issue information is replaced with the imported feature file's data (summaries, steps, tags, ...). Having an option at hand for disabling this behaviour would be useful.

> The jira ticket title is altered too, although I just wanted to upload the Feature with the background steps together. So either I dont upload anything or my tickets are altered completely (title, tags, cucumber steps), but I wished only the steps to be uploaded or altered.

_Originally posted by @alexviz7 in https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/86#issuecomment-1619598484_

**Comment by csvtuda** [comment]
Related to #83.

**Comment by csvtuda** [comment]
Hey @alexviz7, I just released version 4.0.0, which now automatically backups the issues' summaries. Should the imported feature file change them, they will be reset afterwards. Can you check if this works for you? If it does, I will add more backup options (description, labels).

**Comment by csvtuda** [comment]
Ok thank you for confirming, I will add label backups and description backups then in the next few days.
I mostly only have access to a cloud instance and was unsure if this approach of reverting import changes works for server instances too. I will ping you again once it's done.

**Comment by alexviz7** [comment]
Also test execution files now have as an assignee the standard assignee of the project, which is the product owner, but not the one with the Jira PAT, which is me. This was not the case with the previous version.

**Comment by alexviz7** [comment]
Creating any jira ticket manually will have the assignee input field filled with the name of the product owner, so Its not an issue perse. However with the previous plugin versions the ticket created by the plugin had my name as an assignee as it was my PAT that was used.

**Comment by alexviz7** [comment]
issue with labels and assignee is still reproducible with the version 4.0.1

**Comment by alexviz7** [comment]
> Creating any jira ticket manually will have the assignee input field filled with the name of the product owner, so Its not an issue perse. However with the previous plugin versions the ticket created by the plugin had my name as an assignee as it was my PAT that was used.

I think it is a minor issue since I will use fixed test execution files instead of generating new ones each time.

**Comment by alexviz7** [comment]
Hi

> 

Hi how is the progress going?

**Comment by csvtuda** [comment]
I'm working on it, but life has been busy. It's taking a little bit longer because I need to introduce new options, and I'm careful aroud new options to prevent a series of breaking bug fix changes.

**Comment by csvtuda** [comment]
Hey @alexviz7,

Version `4.0.2` is now released and should include a fix which resets the labels to their original set after a successful feature file import.

The new version does not include any updates to your assignee problem, though.

Can you confirm if the label reset works?

**Comment by csvtuda** [comment]
Hey @alexviz7,

version `4.0.3` should fix the error.

**Comment by alexviz7** [comment]
I run various tests with or without test execution file and I couldn't find a bug anymore. It works! Ticket can be closed.
